version: "3"

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    volumes:
      - vol:/app
    ports:
      - "443:443"


  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    env_file:
      - .env




  wordpress:
    build: ./requirements/wordpress/
    volumes:
      - vol:/app
    container_name: wordpress
    env_file:
      - .env
    depends_on:
      - mariadb

volumes:
  vol:
